### ISSUE TITLE
PSR-4: Autoloader

### ISSUE THREAD

**Issue by lakow** [SafeToPay/PHP#1]
Quando o projeto, será atualizado para suportar a PSR-4?

**Comment by LucasDiogo96** [comment]
A SDK já está sendo atualizada para suportar PSR-4, em breve publicaremos.

Caso possua alguma dúvida, pode nos contatar por email:

integracao@safe2pay.com.br.

**Comment by LucasDiogo96** [comment]
Publicado a versão com  PSR-4

O comando para instalação via composer está na documentação

Caso possua alguma dúvida, pode nos contatar por email:

integracao@safe2pay.com.br.
