### ISSUE TITLE
Erro de VisitorId

### ISSUE THREAD

**Issue by trialforce** [SafeToPay/PHP#12]
Na linha 62 do arquivo Safe2Pay\Models\Transactions\Base.php é acessada a variável  VisitorId, mas no cabeçalho é criada VisitorID.

**Comment by felipemcoelho** [comment]
Boa tarde, Eduardo. 
Desculpe, não entendi bem a solicitação. 
O VisitorId é um parâmetro que é [gerado pelo nosso script de antifraude](https://developers.safe2pay.com.br/references/antifraud/script), que deve ser enviado no corpo das transações, mas não tem relação com os cabeçalhos da requisição.

**Comment by trialforce** [comment]
Tranquilo Felipe, acho que ão fui bem claro.

O que acontece é que na definição da classe está VisitorID com D maisculo, e o get e o set esta com VisitorId com D minusculo dai dispara um warning que a variavel VisitorId (minusculo) não esta declarada porque a declarada é a VisitorID (maisculo).

**Comment by felipemcoelho** [comment]
Boa tarde, Eduardo.
Havia aceito um PR e por descuido não tinha reparado nisso. Peço desculpas pelo transtorno.
Já fizemos a correção no repositório e no pacote, basta dar um `composer update` no seu projeto.   

Obrigado pela ajuda!
