### ISSUE TITLE
Método PaymentRequest::Refund está com switch invertido

### ISSUE THREAD

**Issue by faneis** [SafeToPay/PHP#4]
Boa tarde,

reparei que o método para cancelar um pagamento está com o switch do tipo de pagamento invertido. Quando passamos CREDIT está enviando para DebitCard/Cancel e quando passamos DEBIT está enviando para CreditCard/Cancel.

**Comment by felipemcoelho** [comment]
Olá, faneis. Corrigido no repositório e no Composer. Por favor, dê um update nas suas dependências. Obrigado por sinalizar.
