### ISSUE TITLE
[InvalidArgumentException] Could not find a version of package safe2pay/sdk matching your minimum-stability (stable).

### ISSUE THREAD

**Issue by raulamoretti** [SafeToPay/PHP#5]
Ao tentar executar

composer require safe2pay/sdk

[InvalidArgumentException]                                                                                                     
  Could not find a version of package safe2pay/sdk matching your minimum-stability (stable). Require it with an explicit versio  
  n constraint allowing its desired stability.   

Acredito que tem que ter um commit com um versão "especial"

**Comment by raulamoretti** [comment]
"name": "laravel/laravel",^M
    "description": "The Laravel Framework.",^M
    "keywords": ["framework", "laravel"],^M
    "license": "MIT",^M
    "type": "project",^M
    "require": {^M
        "php": ">=7.0.0",^M
        "barryvdh/laravel-cors": "^0.11.0",^M
        "barryvdh/laravel-ide-helper": "^2.4",^M
        "fideloper/proxy": "^4.3",^M
        "iugu/iugu": "^1.0",^M
        "laravel/framework": "5.8.*",^M
        "laravel/tinker": "~1.0",^M
        "league/flysystem-aws-s3-v3": "^1.0",^M
        "phaza/laravel-postgis": "^3.1"^M
    },^M
    "require-dev": {^M

**Comment by felipemcoelho** [comment]
Retirei a obrigatoriedade de estabilidade mínima do pacote. Por favor, tente instalar novamente pelo composer.

**Comment by rminossi** [comment]
Olá, o mesmo está ocorrendo comigo ao tentar instalar a integração via composer:

```
[InvalidArgumentException]

Could not find a version of package safe2pay/sdk matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.
```

Como proceder?

Sds.,
Rafael Minossi

**Comment by felipemcoelho** [comment]
@rminossi, veja se você tem definida a estabilidade mínima definida no seu composer.json, por ex.:

`"minimum-stability": "dev"`
