### ISSUE TITLE
Adicionando IsApplyInterest, InterestRate e SoftDescriptor

### ISSUE THREAD

**Issue by g1245** [SafeToPay/PHP#9]
https://github.com/SafeToPay/PHP/blob/31022c2b288ab4e2d92a1b2c70a256b0a60de291/lib/Models/Payment/CreditCard.php#L9

Validando a documentação da API encontrei uma divergência na sdk para PHP: https://developers.safe2pay.com.br/references/Payment/payment_credit

Faltam adicionar os parâmetros IsApplyInterest, InterestRate e SoftDescriptor. Ou como eu defino esses valores quando é uma transação de cartão de crédito?

**Comment by gabrielvgarcia** [comment]
Olá,
Subimos uma nova versão com esses parâmetros na inicialização do cartão de crédito, por favor, atualize o pacote.
